name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  UnitTest:
    name: (${{ matrix.os }} on ${{ matrix.lisp }}) | UnitTest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin, ecl]
        os: [ubuntu-latest]
        target:
        - normal
    steps:
      - uses: actions/checkout@v1
      - name: Installing ${{ matrix.lisp }}
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Update $PATH
        run: |
          echo $PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Check $PATH
        run: echo $PATH
      - name: make test
        run: |
          ros config set dynamic-space-size 4gb
          make test